# Dependencies
markdown:         kramdown
highlighter:      pygments
gems:
  - jemoji
  - jekyll-archives
  - jekyll-paginate

# Setup
title:            Devcember
tagline:          'a gaudy celebration of web specification'
description:      'a gaudy celebration of web specification'
url:              http://devcember.com
baseurl:          /

author:
  name:           'BigBlueHat'
  url:            http://bigbluehat.com/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/BigBlueHat/devcember
