# Dependencies
markdown:         redcarpet
highlighter:      pygments
gems:
  - jemoji
  - jekyll-archives

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Dev<br />cember
tagline:          'Make something. Give it away.'
description:      'Devcember is giving.<br />Make something.<br />Give it away.'
url:              http://devcember.com
baseurl:          /

author:
  name:           'BigBlueHat'
  url:            http://bigbluehat.com/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/BigBlueHat/devcember
